//
//  DeviceDetectionStatus.h
//  MobileMerchant
//
//  Copyright (c) 2013 Elavon Inc. All rights reserved.
//

#ifndef MobileMerchant_DeviceDetectionStatus_h
#define MobileMerchant_DeviceDetectionStatus_h

typedef enum {
    ECCDEVICE_DETECTION_STATUS_BENIGN = 0,
    ECCDEVICE_DETECTION_STATUS_JAILBREAK_CYDIA_INSTALLED_URL_CHECK,
    ECCDEVICE_DETECTION_STATUS_JAILBREAK_CYDIA_INSTALLED_LIBRARY_CHECK,
    ECCDEVICE_DETECTION_STATUS_JAILBREAK_READ_BASH_DIRECTORY,
    ECCDEVICE_DETECTION_STATUS_APPCRACKED_INVALID_INFOPLIST,
    ECCDEVICE_DETECTION_STATUS_APPCRACKED_INFOPLIST_CONTAINS_SIGNERIDENTITY,
    ECCDEVICE_DETECTION_STATUS_APPCRACKED_ENCRYPTION_OFF,
    ECCDEVICE_DETECTION_STATUS_APPCRACKED_ROOT_USER,
    ECCDEVICE_DETECTION_STATUS_APPCRACKED_MISSING_RESOURCES,
    ECCDEVICE_DETECTION_STATUS_DEBUGGER_ATTACHED
} ECCDeviceDetectionStatus;

#endif
